//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NellsWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class bottle
    {
        public bottle()
        {
            this.bottletaglookups = new HashSet<bottletaglookup>();
            this.notes = new HashSet<note>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [Display(Name="Swatch notes")]
        public string SwatchNotes { get; set; }

        [Display(Name = "Coats on swatch")]
        public Nullable<int> SwatchCoats { get; set; }

        [Display(Name = "Storage drawer")]
        public Nullable<int> SwatchDrawer { get; set; }

        [Display(Name = "Date acquired")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateAcquired { get; set; }

        [Display(Name = "Used it?")]
        public bool Used { get; set; }

        [Display(Name = "Got rid of it?")]
        public bool Purged { get; set; }

        [Display(Name = "Acquired by Goonswap or NIPSASS?")]
        public bool Goon { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual drawer drawer { get; set; }
        public virtual ICollection<bottletaglookup> bottletaglookups { get; set; }
        public virtual ICollection<note> notes { get; set; }

    }
}
