//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NellsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bottletag
    {
        public bottletag()
        {
            this.bottletaglookups = new HashSet<bottletaglookup>();
        }
    
        public int ID { get; set; }
        public string TagName { get; set; }
        public Nullable<int> TagType { get; set; }
    
        public virtual ICollection<bottletaglookup> bottletaglookups { get; set; }
        public virtual bottletagtype bottletagtype { get; set; }
    }
}
