//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NellsWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class brand
    {
        public brand()
        {
            this.bottles = new HashSet<bottle>();
            this.lemmings = new HashSet<lemming>();
            this.ordereds = new HashSet<ordered>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Brand name")]
        public string Name { get; set; }

        [Display(Name = "Country of origin")]
        public string OriginCountry { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<bottle> bottles { get; set; }
        public virtual ICollection<lemming> lemmings { get; set; }
        public virtual ICollection<ordered> ordereds { get; set; }
    }
}
