//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NellsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lemming
    {
        public int ID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public int LustLevel { get; set; }
        public bool Killed { get; set; }
    
        public virtual brand brand { get; set; }
    }
}
